### ISSUE TITLE
Issues with bootstrap4 styling 

### ISSUE THREAD

**Issue by zorar4ik** [WilHall/gretel#14]
Hi, I am using Gretel v. 3.0.9
`gretel (3.0.9)`
I am trying to set style to bootstrap4 accordingly to documentation
`breadcrumbs separator: "&nbsp; &rsaquo; &nbsp;", style: :bootstrap4, display_single_fragment: true, semantic: true`
However I get this kind of error: 

> Breadcrumbs style :bootstrap4 not found. Use any of [:inline, :ol, :ul, :bootstrap, :foundation5].

@WilHall, Does this mean that `bootstrap == bootstrap4` and if so, then probably It would be better to change guide a bit?

**Comment by MrShemek** [comment]
Can you please show me the line from `Gemfile` that adds `gretel`?

**Comment by zorar4ik** [comment]
Sure. 
<img width="319" alt="gretel_gemfile_lock" src="https://user-images.githubusercontent.com/22009908/54263930-a77fad80-457a-11e9-993e-8eacd2c99695.png">
<img width="372" alt="gretel_gemfile" src="https://user-images.githubusercontent.com/22009908/54263931-a77fad80-457a-11e9-9e42-414e3dec8a7e.png">

**Comment by MrShemek** [comment]
You are using gretel from rubygems.org. The version there is the same as in the following repo:
https://github.com/lassebunk/gretel

However, we decided to create a fork and maintain the gem here (we will also update rubygems version). 

Please replace `gem 'gretel'` with:

```
gem 'gretel', git: 'https://github.com/WilHall/gretel.git', branch: 'develop'
```

Then, everything will work as expected.

**Comment by zorar4ik** [comment]
Okay, got it. Thank you
